### ISSUE TITLE
Ban ?

### ISSUE THREAD

**Issue by Ypotrope** [marcfusch/sos-solus#1]
Bonjour,

Avant de faire fonctionner le script je voulais savoir s'il étai détectable et pouvait nous faire ban de docsolus.

**Comment by marcfusch** [comment]
Salut, tant que tu ne scrape pas la nuit et que tu ne fais pas 20 sujets par jours c'est nickel ( d'où l'implémentation d'une variable contesttime). Je l'ai fait tourner pendant 6 mois sur une machine comme ça et je n'ai jamais eu de soucis.
> détectable
